name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: josephkiok/webrtc-network-traffic-visualizer:latest

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push the Docker image
      run: docker push $IMAGE_NAME
